config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  constraints subdomain: 'admin' do
    scope module: 'admin', as: 'admin' do
      root to: 'dashboard#show'
    end
  end

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/application_controller.rb
module Admin
  #
  class ApplicationController < ::ApplicationController
    layout 'admin'
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  #
  class DashboardController < ApplicationController
    def show
    end
  end
end

app/controllers/application_controller.rb
#
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
#
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/blocks/_sidebar.html.slim
.sidebar
  .sidebar__heading Fincastali Hearth
  .sidebar__content
    .sidebar__item
      = link_to 'Dashboard', admin_root_path

    .sidebar__item
      = link_to 'Home Page', ''

app/views/admin/dashboard/show.html.slim
header.header
  h1 Dashboard

app/views/blocks/_footer.html.slim
footer.footer
  .footer__info
    .footer__contact
      .footer__contact__item Email: fincastali@gmail.com
      .footer__contact__item Phone: 555-555-1234

    p.footer__copyright
      | Copyright &copy; 2016 Fincastali Hearth. All Rights Reserved. 
      | Fincastali Hearth is an unincorporated nonprofit association in 
      | accordance with the 
      = link_to 'Kentucky Uniform Unincorporated Nonprofit Association Act',
                'http://www.lrc.ky.gov/statutes/chapter.aspx?id=43992'
      | .

  .footer__nav
    .nav.nav--footer
      = render 'blocks/nav_body'

app/views/blocks/_image_gap.html.slim
.image-gap style="background-image: url('#{gap_image}')"

app/views/blocks/_masthead.html.slim
.masthead
  button.hamburger
    span toggle menu

app/views/blocks/_nav_body.html.slim
= link_to 'Home', root_path,
          class: ['nav__item']

= link_to 'Contact', '',
          class: ['nav__item']

= link_to 'Calendar', '',
          class: ['nav__item']

= link_to 'News', '',
          class: ['nav__item']

= link_to 'Information', '',
          class: ['nav__item']

= link_to 'Resources', '',
          class: ['nav__item']

app/views/blocks/_sidebar.html.slim
.sidebar
  .sidebar__heading Navigation
  nav.nav.nav--sidebar
    = render 'blocks/nav_body'

app/views/layouts/admin.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="Content-Type" content="text/html; charset=utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no"
    = csrf_meta_tags

    title
      = content_for :page_title
      | Admin | Fincastali Hearth

    = stylesheet_link_tag FincastaliWww::CdnUrls::NORMALIZE,
                          media:                   'all'
    = stylesheet_link_tag FincastaliWww::CdnUrls::FONTS_CSS,
                          media:                   'all'
    = stylesheet_link_tag 'admin',
                          media:                   'all'

  body data-controller=controller_name data-action=action_name
    .page
      = render 'admin/blocks/sidebar'

      .page__content
        = yield

    = javascript_include_tag 'admin'

app/views/layouts/application.html.slim
doctype html
html.no-js lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="Content-Type" content="text/html; charset=utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no"
    = csrf_meta_tags

    title
      = content_for :page_title
      | Fincastali Hearth

    = stylesheet_link_tag FincastaliWww::CdnUrls::NORMALIZE,
                          media:                   'all'
    = stylesheet_link_tag FincastaliWww::CdnUrls::FONTS_CSS,
                          media:                   'all'
    = stylesheet_link_tag 'application',
                          'data-turbolinks-track': 'reload',
                          media:                   'all'

    = javascript_include_tag FincastaliWww::CdnUrls::MODERNIZR
    = javascript_include_tag 'application',
                             'data-turbolinks-track': 'reload'

  body data-controller=controller_name data-action=action_name
    .page.bg-white
      = render 'blocks/masthead'
      = render 'blocks/sidebar'

      .page__body.bg-white
        = yield
        
        = render 'blocks/footer'

app/views/pages/home.html.slim
header.header
  video[autoplay loop poster=image_path('pages/home/heading.jpg')]
    source src="/videos/test.mp4" type="video/mp4"
    source type="video/ogg"

  .header__content
    h1 Fincastali Hearth

main.main
  div.page--home__about-us.--margin
    p
      | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis 
      | sagittis aliquet sem, ut vestibulum metus tincidunt eget. Vestibulum 
      | accumsan pellentesque erat, mollis dictum massa varius vitae. 
      | Suspendisse potenti. In efficitur fringilla dolor, vitae ullamcorper 
      | ante sagittis at. Etiam eleifend orci ac egestas scelerisque. 
      | Vestibulum lacinia dolor eu tempus aliquam. Quisque id bibendum 
      | massa, eu auctor sem. Cras tellus quam, luctus vitae dolor faucibus, 
      | tincidunt vehicula velit. Vestibulum pretium ipsum tellus, non semper 
      | metus ornare et. Donec rutrum finibus mauris sed tincidunt. Fusce 
      | nulla justo, consectetur sed sodales id, commodo vel lorem. Maecenas 
      | sagittis orci vitae mauris dapibus condimentum. Fusce fringilla velit 
      | vitae hendrerit semper. Nullam massa libero, tincidunt sed enim id, 
      | lobortis tristique lectus. Mauris varius neque ac tortor iaculis 
      | porta.

    p
      | Nullam sollicitudin nulla leo, ut semper augue tincidunt id. Fusce 
      | vitae tortor sit amet felis laoreet pulvinar. Nunc quis vulputate 
      | ipsum. Quisque non tellus nec urna eleifend condimentum eget eu 
      | ligula. Quisque eu diam felis. Cras eget diam nulla. Donec dapibus 
      | lacinia metus non semper. Lorem ipsum dolor sit amet, consectetur 
      | adipiscing elit. Cum sociis natoque penatibus et magnis dis 
      | parturient montes, nascetur ridiculus mus.

  .row
    section.row__column
      h2 Upcoming Events

      p
        | Nam ut tempus tellus. Fusce vulputate sed sem nec aliquam. Morbi at 
        | tellus consequat, consequat urna in, luctus justo. Phasellus commodo, 
        | neque lacinia commodo sagittis, libero nisl iaculis leo, in mollis sapien 
        | est et nisl. Vestibulum tincidunt venenatis porttitor. Quisque non est 
        | enim. Vivamus aliquet erat ut quam tincidunt, sit amet feugiat quam 
        | molestie. Aenean euismod varius erat tempor convallis. Maecenas at tortor 
        | a nunc pellentesque venenatis at eget mauris. Mauris interdum, augue 
        | efficitur dictum suscipit, velit lorem pellentesque orci, vel fermentum 
        | tellus quam eget eros.

      p
        | Suspendisse tempor nulla convallis, scelerisque tortor eget, tempor 
        | ipsum. Proin tincidunt sit amet nulla quis faucibus. Nullam sem lacus, 
        | aliquam eu condimentum rutrum, vestibulum nec nisi. Proin odio sapien, 
        | malesuada vel ullamcorper eget, ultrices eget dolor. Sed sodales iaculis 
        | enim at laoreet. Sed sit amet pretium massa. Vivamus at quam leo. Fusce 
        | odio sapien, mollis at luctus ac, aliquam et elit. Cras accumsan sem id 
        | nibh mattis, non tincidunt est viverra. Maecenas faucibus vel erat ac 
        | fermentum. Duis arcu elit, finibus nec dui a, volutpat commodo eros. 
        | Fusce ullamcorper maximus pulvinar. Donec vitae varius tortor, eget 
        | faucibus dolor. Morbi cursus dui a augue tincidunt hendrerit. Fusce 
        | volutpat erat nibh, a mattis purus dictum sit amet.

    section.row__column
      h2 Recent News

      p 
        | Integer laoreet nulla vitae luctus sagittis. Curabitur lacus nibh, 
        | malesuada ac laoreet et, elementum id felis. Ut euismod sem quis nunc 
        | accumsan consequat. Pellentesque habitant morbi tristique senectus et 
        | netus et malesuada fames ac turpis egestas. Integer at quam eu eros 
        | blandit sagittis. Morbi suscipit est id tortor lacinia, quis interdum 
        | erat elementum. Ut condimentum fringilla nisl, eu eleifend eros lacinia 
        | eu. Donec et rutrum ex, 
        = link_to 'eget consectetur quam', ''
        | . Aenean a sodales enim. In 
        | scelerisque orci tristique, pellentesque dui id, sollicitudin odio. Nulla 
        | accumsan nulla eu tortor egestas lobortis. Duis vel neque sit amet nibh 
        | condimentum vulputate eu ac tellus. Aliquam porta finibus mi.

      p
        | Sed accumsan est et arcu vestibulum egestas. Quisque bibendum placerat 
        | fringilla. Nulla pharetra sapien est, eget tristique diam pharetra non. 
        | Donec sed sapien pulvinar, venenatis ipsum sollicitudin, aliquet leo. Sed 
        | neque urna, ullamcorper ut suscipit sit amet, efficitur in est. Nullam 
        | rhoncus elit ornare quam placerat rutrum. Vivamus ultricies lectus metus, 
        | non fringilla libero eleifend eu. Nullam auctor, dolor ut mattis 
        | faucibus, dolor nunc blandit justo, dignissim luctus sapien lacus in 
        | risus. Nulla tincidunt aliquam nulla, sed gravida lorem fermentum ac. 
        | Nunc euismod malesuada felis eu efficitur. Vivamus luctus ut elit quis 
        | consequat. Cras hendrerit sem magna, et euismod elit molestie ac.

= render 'blocks/image_gap', gap_image: image_path('pages/home/gap-1.jpg')